packages:
  - apps/*
  - common/*
  - examples/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  eslint: ^9.25.0
  prettier: ^3.5.3
  typescript: ^5.8.3

  # Misc
  zod: ^3.24.3

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.74.4
  "@trpc/client": ^11.1.0
  "@trpc/tanstack-react-query": ^11.1.0
  "@trpc/server": ^11.1.0

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.0
    "@types/react-dom": ^19.1.0
 
  tailwind4:
    tailwindcss: ^4.1.4
    "@tailwindcss/postcss": ^4.1.4
